### ISSUE TITLE
ENOENT: No such file or directory, open data/tmdb_dump_movie_ids.json

### ISSUE THREAD

**Issue by EliasPereirah** [transitive-bullshit/populate-movies#2]
Hello when I run: `npx tsx src/download-data-dumps.tsx`
I received the following error:

`Could not find module '/home/ubuntu/transitive/populate-movies/src/download-data-dumps.tsx`

Then I run `npx tsx src/download-data-dumps.ts`

And it seems to work, but when I run the next command:  `npx tsx src/populate-tmdb-movie-dump.ts`
I get the following error:  `Error: ENOENT: No such file or directory, open 'data/tmdb_dump_movie_ids.json`

**Comment by transitive-bullshit** [comment]
Something in your node.js setup seems incorrect. You can add some debug statements to `src/download-data-dumps.tsx` to make sure things are working correctly. If `data/tmdb_dump_movie_ids.json` doesn't exist, then that script didn't run correctly.
