### ISSUE TITLE
populate-rt-movies.ts not processing movies-##.json

### ISSUE THREAD

**Issue by otoolejp** [transitive-bullshit/populate-movies#3]
I'm not sure what else to provide as far as information. All previous processes seem to have been completed correctly. The movies-#.json and tmdb-#.json files are present in /old. At the end rt-movies.json is present, but empty other than brackets. Process completed in about 10 seconds. Thanks for your help, I'm very excited to be able to get this process working.

Output:
d:\populate-movies-main>npx tsx src/populate-rt-movies.ts
(node:16868) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
loading RT movies from cache (out/rt-movies.json)
loading OMDB movies from cache (out/omdb-movies.json)
warn: unable to load OMDB movie cache (out/omdb-movies.json)
You can safely ignore this warning if you haven't run `populate-omdb-movies.ts`.
[Error: ENOENT: no such file or directory, open 'd:\populate-movies-main\out\omdb-movies.json'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'd:\\populate-movies-main\\out\\omdb-movies.json'
}
loaded 0 RT movies from cache (out/rt-movies.json)
TODO

populating 21231 movies in batch 3 (out/movies-3.json)

batch 3 done { numMovies: 21231, numRTMoviesDownloaded: 0, numRTMoviesTotal: 0 }

populating 20427 movies in batch 4 (out/movies-4.json)

batch 4 done { numMovies: 20427, numRTMoviesDownloaded: 0, numRTMoviesTotal: 0 }

populating 20366 movies in batch 5 (out/movies-5.json)

batch 5 done { numMovies: 20366, numRTMoviesDownloaded: 0, numRTMoviesTotal: 0 }

populating 15642 movies in batch 6 (out/movies-6.json)

batch 6 done { numMovies: 15642, numRTMoviesDownloaded: 0, numRTMoviesTotal: 0 }

populating 18466 movies in batch 7 (out/movies-7.json)

batch 7 done { numMovies: 18466, numRTMoviesDownloaded: 0, numRTMoviesTotal: 0 }

populating 13063 movies in batch 8 (out/movies-8.json)

batch 8 done { numMovies: 13063, numRTMoviesDownloaded: 0, numRTMoviesTotal: 0 }

populating 14762 movies in batch 9 (out/movies-9.json)

batch 9 done { numMovies: 14762, numRTMoviesDownloaded: 0, numRTMoviesTotal: 0 }

populating 12610 movies in batch 10 (out/movies-10.json)

batch 10 done { numMovies: 12610, numRTMoviesDownloaded: 0, numRTMoviesTotal: 0 }

populating 9826 movies in batch 11 (out/movies-11.json)

batch 11 done { numMovies: 9826, numRTMoviesDownloaded: 0, numRTMoviesTotal: 0 }

populating 10885 movies in batch 12 (out/movies-12.json)

batch 12 done { numMovies: 10885, numRTMoviesDownloaded: 0, numRTMoviesTotal: 0 }

populating 10982 movies in batch 13 (out/movies-13.json)

batch 13 done { numMovies: 10982, numRTMoviesDownloaded: 0, numRTMoviesTotal: 0 }

populating 9905 movies in batch 14 (out/movies-14.json)

batch 14 done { numMovies: 9905, numRTMoviesDownloaded: 0, numRTMoviesTotal: 0 }

populating 9733 movies in batch 15 (out/movies-15.json)

batch 15 done { numMovies: 9733, numRTMoviesDownloaded: 0, numRTMoviesTotal: 0 }

populating 7993 movies in batch 16 (out/movies-16.json)

batch 16 done { numMovies: 7993, numRTMoviesDownloaded: 0, numRTMoviesTotal: 0 }

populating 7382 movies in batch 17 (out/movies-17.json)

batch 17 done { numMovies: 7382, numRTMoviesDownloaded: 0, numRTMoviesTotal: 0 }

populating 5289 movies in batch 18 (out/movies-18.json)

batch 18 done { numMovies: 5289, numRTMoviesDownloaded: 0, numRTMoviesTotal: 0 }

populating 4911 movies in batch 19 (out/movies-19.json)

batch 19 done { numMovies: 4911, numRTMoviesDownloaded: 0, numRTMoviesTotal: 0 }

populating 5047 movies in batch 20 (out/movies-20.json)

batch 20 done { numMovies: 5047, numRTMoviesDownloaded: 0, numRTMoviesTotal: 0 }

populating 4802 movies in batch 21 (out/movies-21.json)

batch 21 done { numMovies: 4802, numRTMoviesDownloaded: 0, numRTMoviesTotal: 0 }

populating 4950 movies in batch 22 (out/movies-22.json)

batch 22 done { numMovies: 4950, numRTMoviesDownloaded: 0, numRTMoviesTotal: 0 }

populating 4494 movies in batch 23 (out/movies-23.json)

batch 23 done { numMovies: 4494, numRTMoviesDownloaded: 0, numRTMoviesTotal: 0 }

done {
  numMoviesTotal: 232766,
  numRTMoviesDownloadedTotal: 0,
  numRTMoviesTotal: 0
}

**Comment by transitive-bullshit** [comment]
You need to process `omdb` or `flickmetrix` first before running `populate-rt-movies` in order to retrieve RT URLs. This isn't ideal, and neither of these providers gives the correct RT URL 100% of the time. RT URLs have some patterns, but there are lots of exceptions, which makes them harder to predict.
